apiVersion: v1
kind: Secret
metadata:
  name: supply-chain-secrets
type: Opaque
stringData:
  # Postgres Credentials
  POSTGRES_USER: "osvuser"
  POSTGRES_PASSWORD: "CHANGE_ME"
  POSTGRES_DB: "osv_db"

  # JFrog Artifactory credentials
  JFROG_URL: "https://your-artifactory-instance.jfrog.io/artifactory"
  JFROG_USER: "admin"
  JFROG_TOKEN: "CHANGE_ME_API_TOKEN"

  # CrowdStrike Falcon credentials
  CS_CLIENT_ID: "CHANGE_ME_CLIENT_ID"
  CS_CLIENT_SECRET: "CHANGE_ME_CLIENT_SECRET"
  CS_BASE_URL: "https://api.crowdstrike.com"
