apiVersion: v1
kind: Secret
metadata:
  name: supply-chain-secrets
type: Opaque
stringData:
  # Postgres Credentials
  POSTGRES_USER:     "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_DB:       "${POSTGRES_DB}"

  # JFrog Artifactory credentials
  JFROG_URL:   "${JFROG_URL}"
  JFROG_USER:  "${JFROG_USER}"
  JFROG_TOKEN: "${JFROG_TOKEN}"

  # CrowdStrike Falcon credentials
  CS_CLIENT_ID:     "${CS_CLIENT_ID}"
  CS_CLIENT_SECRET: "${CS_CLIENT_SECRET}"
  CS_BASE_URL:      "${CS_BASE_URL}"
